services:
  entersys-admin:
    build: .
    container_name: entersys-admin
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.entersys.mx/api
      NEXT_PUBLIC_APP_URL: https://admin.entersys.mx
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entersys-admin.rule=Host(`admin.entersys.mx`)"
      - "traefik.http.routers.entersys-admin.entrypoints=websecure"
      - "traefik.http.routers.entersys-admin.tls.certresolver=letsencrypt"
      - "traefik.http.services.entersys-admin.loadbalancer.server.port=3002"

networks:
  traefik:
    external: true
